In [1]:
import numpy as np

In [2]:
my_list=[1,2,3,4]
my_list

[1, 2, 3, 4]

In [3]:
type(my_list)

list

In [4]:
array=np.array(my_list,dtype=int)
my_list

[1, 2, 3, 4]

In [5]:
type(array)

numpy.ndarray

In [6]:
array.ndim
array.shape

(4,)

In [7]:
array2=array.reshape(2,2)
array2

array([[1, 2],
       [3, 4]])

In [8]:
array4=array.reshape(2,-1)
array4

array([[1, 2],
       [3, 4]])

In [9]:
my_list2=[1,2,3,4]
my_list3=[5,6,7,8]
my_list4=[9,10,11,12]

In [10]:
mul_array=np.array([my_list2,my_list3,my_list4])
mul_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:
mul_array.shape

(3, 4)

In [12]:
mul_array2=mul_array.reshape(6,-1)
mul_array2

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [13]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
r=range(16)
r

range(0, 16)

In [15]:
r2=np.arange(16)
r2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [16]:
r3=r2.reshape(4,2,-1)
r3

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]]])

In [17]:
x=np.array([1,2,3,4,5],dtype=np.float64)
x

array([1., 2., 3., 4., 5.])

In [18]:
x.itemsize

8

In [19]:
x2=np.array([6,7,8,9,10],dtype=np.float64)
x2

array([ 6.,  7.,  8.,  9., 10.])