In [2]:
print("hello world!")

hello world!


In [3]:
## Jupyter notebook

In [4]:
import numpy as np

In [5]:
myList = [1, 2, 3, 4, 5, 6]

In [6]:
array = np.array(myList, dtype = int)

In [7]:
print(array)

[1 2 3 4 5 6]


In [8]:
print(type(array))

<class 'numpy.ndarray'>


In [9]:
print(array.ndim)

1


In [10]:
print(array.shape)

(6,)


In [11]:
array2 = array.reshape(3,2)

In [12]:
print(array2)

[[1 2]
 [3 4]
 [5 6]]


In [13]:
print(array.shape)

(6,)


In [14]:
array.shape

(6,)

In [15]:
array3 = array.reshape(3,-1)

In [16]:
print(array3)

[[1 2]
 [3 4]
 [5 6]]


In [17]:
array3.ndim
array3.shape

(3, 2)

In [18]:
myList2 = [1,2,3,4,5]
myList3 = [11,12,13,14,15]
myList4 = [21,22,23,24,25]

In [19]:
mul_array = np.array([myList2, myList3, myList4])
print(mul_array)
print(mul_array.shape)

[[ 1  2  3  4  5]
 [11 12 13 14 15]
 [21 22 23 24 25]]
(3, 5)


In [20]:
mul_array2 = mul_array.reshape(5,-1)
print(mul_array2)

[[ 1  2  3]
 [ 4  5 11]
 [12 13 14]
 [15 21 22]
 [23 24 25]]


In [21]:
a = np.array([[1,2,3],[4,5,6]])
print(a.shape)

(2, 3)


In [22]:
a.shape = (3,2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [23]:
r = range(24)
print(r)

range(0, 24)


In [24]:
r2 = np.arange(24)
print(r2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [25]:
r3 = r2.reshape(6,4,1)
print(r3)
print(r3.shape)

[[[ 0]
  [ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]
  [ 7]]

 [[ 8]
  [ 9]
  [10]
  [11]]

 [[12]
  [13]
  [14]
  [15]]

 [[16]
  [17]
  [18]
  [19]]

 [[20]
  [21]
  [22]
  [23]]]
(6, 4, 1)


In [26]:
x = np.array([1,2,3,4,5], dtype = np.int8)
print(x.itemsize)

1


In [27]:
x2 = np.array([1,2,3,4,5], dtype = np.float32)
print(x2.itemsize)

4


In [28]:
x3 = np.array([[1,2,3,4,5], [1,2,3,4,5]], dtype = np.float64)
x4 = np.array([[11,12,13,14,15], [21,22,23,24,25]], dtype = np.float64)
print(x3)
print(x4)
print(x3.itemsize)

[[1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]]
[[11. 12. 13. 14. 15.]
 [21. 22. 23. 24. 25.]]
8


In [29]:
print(x3+ x4)
print(np.add(x3, x4))

[[12. 14. 16. 18. 20.]
 [22. 24. 26. 28. 30.]]
[[12. 14. 16. 18. 20.]
 [22. 24. 26. 28. 30.]]


In [30]:
print(x3 - x4)
print(np.subtract(x3, x4))

[[-10. -10. -10. -10. -10.]
 [-20. -20. -20. -20. -20.]]
[[-10. -10. -10. -10. -10.]
 [-20. -20. -20. -20. -20.]]


In [31]:
print(x4)
print(np.sum(x4))
print(np.sum(x4, axis = 0))
print(np.sum(x4, axis = 1))

[[11. 12. 13. 14. 15.]
 [21. 22. 23. 24. 25.]]
180.0
[32. 34. 36. 38. 40.]
[ 65. 115.]
